# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhsa', '0008_auto_20160228_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfolder',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userfolder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
