# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fhsa', '0015_auto_20160316_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='folders',
        ),
        migrations.RemoveField(
            model_name='result',
            name='id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='name',
        ),
        migrations.AddField(
            model_name='result',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='url',
            field=models.URLField(default=datetime.datetime(2016, 3, 16, 20, 15, 55, 9000, tzinfo=utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
