# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhsa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
