# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fhsa', '0007_auto_20160228_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfolder',
            name='creator',
        ),
        migrations.AddField(
            model_name='userfolder',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
