# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fhsa', '0011_userfolder_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfolder',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 3, 2, 20, 36, 52, 295343, tzinfo=utc), max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
