# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fhsa', '0014_auto_20160316_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='folders',
        ),
        migrations.AddField(
            model_name='result',
            name='folders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fhsa.UserFolder'),
        ),
    ]
