# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhsa', '0006_userfolder_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfolder',
            name='creator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
