# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhsa', '0013_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='folders',
            field=models.ManyToManyField(to='fhsa.UserFolder'),
        ),
        migrations.AddField(
            model_name='result',
            name='name',
            field=models.URLField(null=True),
        ),
    ]
